// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Current  int64  `json:"Current,default=1,optional"`
	PageSize int64  `json:"PageSize,default=10,optional"`
	Id       string `json:"Id"`
}
