// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Current  int64  `json:"current,default=1,optional"`
	PageSize int64  `json:"page_size,default=10,optional"`
	Id       string `json:"id"`
}
